# Generated by Django 5.0 on 2023-12-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotList',
            fields=[
                ('man', models.CharField(primary_key=True, serialize=False, verbose_name='ФИО сотрудника')),
                ('spot', models.CharField(choices=[(None, 'Выберите участок'), ('плазма', 'плазма')])),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('deadline', models.DateField()),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.spotlist')),
            ],
        ),
    ]
